config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'about' => 'home#about'

  devise_for :mentors
  devise_for :students

  resources :skills
  resources :bookmarks

  namespace :mentoring do
    resources :students, only: [:index, :show] do
      resources :appointments, only: [:show, :new, :create] do
        get :record
        post :conclude
      end
    end
    resources :appointments, only: [:index]
    resources :questions, only: [:create, :destroy]
  end


end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :mentor
  belongs_to :student
  has_many :questions, dependent: :destroy
  
  enum catgegory: [ :scheduled, :make_up, :impromptu ]
  
  def conclude
    self.finished_at = Time.now
    save
  end
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :skill
  belongs_to :mentor
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :skills
  has_many :students
  has_many :bookmarks
  has_many :appointments

  before_create :set_mentor_role

  def set_mentor_role
    self.role = "mentor"
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :appointment
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :mentor
  has_many   :bookmarks
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :mentor
  
  has_many :appointments

  before_create :set_student_role

  def set_student_role
    self.role = "student"
  end
  
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate!
    :authenticate_mentor! || :authenticate_student
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate!

  def index
    @new_bookmark = Bookmark.new
    @bookmarks = Bookmark.all
  end

  def new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    # Temporary Auth Logic for Mentor
    redirect_to :back and return unless current_mentor
    @bookmark.mentor = current_mentor

    @bookmark.save

    redirect_to :back
  end

  def show
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :skill_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/mentoring/appointments_controller.rb
class Mentoring::AppointmentsController < ApplicationController
  def index
    @appointments = current_mentor.appointments.includes(:student).order("students.first_name")
  end

  def show
    # will show specific appointment of a student
    @student = Student.find(params[:student_id])
    @appointment = Appointment.find(params[:id])
    @questions = @appointment.questions
  end

  def new
    @appointment = Appointment.new
    @student = Student.find(params[:student_id])
  end
  
  def create
    @student = Student.find(params[:student_id])
    @appointment = Appointment.new(appointment_params)
    @appointment.student = @student
    @appointment.mentor = current_mentor
    
    @appointment.save
    redirect_to mentoring_student_appointment_record_path(@student, @appointment)
  end
  
  def record
    @appointment = Appointment.find(params[:appointment_id])
    @student = Student.find(params[:student_id])
    @questions = @appointment.questions
  end
  
  def conclude
    @appointment = Appointment.find(params[:appointment_id])
    @student = Student.find(params[:student_id])
    
    @appointment.conclude
    
    redirect_to mentoring_students_path
  end
  
  private
  
  def appointment_params
    params.require(:appointment).permit(:category)
  end
end

app/controllers/mentoring/questions_controller.rb
class Mentoring::QuestionsController < ApplicationController

  def create
    @question = Question.new(question_params)

    @question.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def question_params
    params.require(:question).permit(:appointment_id, :description, :answer)
  end
end

app/controllers/mentoring/students_controller.rb
class Mentoring::StudentsController < ApplicationController
  def index
    @students = current_mentor.students
  end

  def show
    @student = Student.find(params[:id])
    @appointments = @student.appointments
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    @question = Question.new(question_params)

    @question.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def question_params
    params.require(:question).permit(:appointment_id, :description, :answer)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @new_skill = Skill.new
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
    @skill_bookmarks = @skill.bookmarks
  end

  def create
    @skill = Skill.new(skill_params)

    # Temporary Auth Logic for Mentor
    redirect_to :back and return unless current_mentor
    @skill.mentor = current_mentor

    @skill.save

    redirect_to :back
  end

  private

  def skill_params
    params.require(:skill).permit(:name, :description)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = current_mentor.students
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    # Will need a more robust solution, at some point.
    current_mentor || current_student
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/mentoring/appointments/_appointment.html.erb
<div>
  <%= link_to mentoring_student_appointment_path(appointment.student, appointment) do %>
    <div><%= "#{appointment.student.name} #{appointment.created_at.strftime('%m/%d/%Y')}" %></div>
  <% end %>
</div>

app/views/mentoring/appointments/edit.html.erb
<h1>Edit Appointment</h1>
<div>
  <%= render partial: 'questions/question', collection: @questions %>
</div>

app/views/mentoring/appointments/index.html.erb
<h1>Appointments</h1>

<div>
  <%#= link_to 'New Appointment', new_mentoring_student_appointment_path %>
</div>
<div>
  <%= render partial: 'appointment', collection: @appointments %>
</div>

app/views/mentoring/appointments/new.html.erb
<h1>New Appointment</h1>
<div>
  Student: <%= @student.name %>
</div>

<%= form_for [:mentoring, @student, @appointment] do |f| %>
  <%= f.radio_button :category, 1, checked: true %>
  <%= label :category, 'Scheduled' %>
  <%= f.radio_button :category, 2 %>
  <%= label :category, 'Make Up' %>
  <%= f.radio_button :category, 3 %>
  <%= label :category, 'Impromptu' %>
  
  <%= f.submit "Start" %>
<% end %>

<div><%= link_to "Start", mentoring_student_appointments_path(@student, @appointment), method: :post %></div>

app/views/mentoring/appointments/record.html.erb
<h1>Record</h1>
<h2>Student: <%= @student.name %></h2>

<p>
  Start Time: <%= @appointment.created_at.to_time.strftime("%H:%M %P") %>
</p>

<div>
  <%= render partial: 'mentoring/questions/form', locals: { appointment: @appointment, question: Question.new, student: @student}, as: :question %>
</div>

<div class="questions">
  <%= render partial: 'mentoring/questions/question', collection: @questions %>
</div>

<div>
  <%= link_to "Finish", mentoring_student_appointment_conclude_path(@student, @appointment), method: :post %>
</div>

app/views/mentoring/appointments/show.html.erb
<h1>Appointment: <%= @appointment.student.name %></h1>
<h4>On: <%= @appointment.created_at.strftime('%m/%d/%Y') %></h4>

<p>
  Started At: <%= @appointment.created_at.to_time.strftime("%H:%M %P") %>
</p>
<p>
  Concluded At: <%= @appointment.finished_at.to_time.strftime("%H:%M %P") if @appointment.finished_at%>
</p>

<div class="questions">
  <%= render partial: 'mentoring/questions/question', collection: @questions %>
</div>

app/views/mentoring/questions/_form.html.erb
<h2>Add Questions</h2>

<%= form_for [:mentoring, question], remote: true do |f| %>
  <div class="">
    <%= f.text_field :description, placeholder: "Enter a Question", id: "new-question-description" %>
  </div>
  <div class="">
    <%= f.text_area :answer, placeholder: "Answer to Question", id: "new-question-answer" %>
  </div>
  <%= f.hidden_field :appointment_id, value: appointment.id %>
  <%= f.hidden_field :student_id, value: student.id %>
  <%= f.hidden_field :type, value: "question", id: "new-question-hidden-type" %>
  <div class="">
    <%= f.submit "Add", id: "new-question-button" %>
  </div>
<% end %>

app/views/mentoring/questions/_question.html.erb
<div id="question-<%=question.id%>">
  <div>
    Question: <%= question.description %>
  </div>
  <div>
    Answer: <%= question.answer %>
  </div>
  <div>
    <%= link_to "edit", "#" %>
    <%= link_to "delete", [:mentoring, question], method: :delete, remote: true %>
  </div>
</div>
<br />

app/views/mentoring/questions/create.js.erb
$('.questions').prepend("<%= escape_javascript(render partial: 'mentoring/questions/question', locals: {question: @question}) %>");

app/views/mentoring/students/_student.html.erb
<div class="student">
  <%= link_to(mentoring_student_path(student)) do %>
    <%= student.first_name + ' ' + student.last_name %>
  <% end %>
  &nbsp;&nbsp;&nbsp;
  <%= link_to "New Appointment" , new_mentoring_student_appointment_path(student)  %>
</div>

app/views/mentoring/students/index.html.erb
<h1>Your Students</h1>

<div class="mentor-students">
  <%= render partial: 'mentoring/students/student', collection: @students %>
</div>

app/views/mentoring/students/show.html.erb
<h1>Student:  <%= @student.first_name %></h1>

<div>
  <%= link_to 'New Appointment', new_mentoring_student_appointment_path(@student) %>
</div>
<div>
  <%= render partial: 'mentoring/appointments/appointment', collection: @appointments %>
</div>

app/views/mentors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/questions/_form.html.erb
<%= form_for(question, remote: true) do |f| %>
    <%= f.text_field :description, placeholder: "Enter a Question", id: "new-question-description" %>
    <%= f.text_field :answer, placeholder: "Answer to Question", id: "new-question-answer" %>
    <%= f.hidden_field :appointment_id, value: appointment.id %>
    <%= f.hidden_field :type, value: "question", id: "new-question-hidden-type" %>
    <%= f.submit "Add", id: "new-question-button" %>
<% end %>

app/views/questions/_question.html.erb
<div id="question-<%=question.id%>">
  <div>
    Question: <%= question.description %>
  </div>
  <div>
    Answer: <%= question.answer %>
  </div>
  <div>
    <%= link_to "edit", "#" %>
    <%= link_to "delete", question_path(question.id), method: :delete, remote: true %>
  </div>
</div>
<br />

app/views/questions/destroy.js.erb
$('#question-<%=@question.id%>').remove();

app/views/skills/index.html.erb
<h1>Skills</h1>

<%= form_for @new_skill do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit "Add" %>
<% end %>

<% @skills.each do |skill| %>
  <p>
    <%= link_to skill.name, skill %>
  </p>
<% end %>

app/views/skills/show.html.erb
<h1> <%= @skill.name %> </h1>
<% @skill.bookmarks.each do |bookmark| %>
  <ul>
    <li> <%= bookmark.url %> </li>
  </ul>
<% end %>

app/views/students/_student.html.erb
<div class="student">
  <%= link_to(student) do %>
    <p><%= student.first_name + ' ' + student.last_name %></p>
  <% end %>
</div>