config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'about' => 'home#about'

  devise_for :mentors
  devise_for :students

  resources :skills
  resources :bookmarks

  namespace :mentoring do
    resources :students, only: [:index, :show] do
      resources :appointments, only: [:show, :new, :create] do
        get :record
        post :conclude
      end
    end
    resources :appointments, only: [:index]
    resources :questions, only: [:create, :destroy]
  end


end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :mentor
  belongs_to :student
  has_many :questions, dependent: :destroy
  
  enum catgegory: [ :scheduled, :make_up, :impromptu ]
  
  def conclude
    self.finished_at = Time.now
    save
  end
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :skill
  belongs_to :mentor
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :skills
  has_many :students
  has_many :bookmarks
  has_many :appointments

  before_create :set_mentor_role

  def set_mentor_role
    self.role = "mentor"
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :appointment
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :mentor
  has_many   :bookmarks
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :mentor
  
  has_many :appointments

  before_create :set_student_role

  def set_student_role
    self.role = "student"
  end
  
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate!
    :authenticate_mentor! || :authenticate_student
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate!

  def index
    @new_bookmark = Bookmark.new
    @bookmarks = Bookmark.all
  end

  def new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    # Temporary Auth Logic for Mentor
    redirect_to :back and return unless current_mentor
    @bookmark.mentor = current_mentor

    @bookmark.save

    redirect_to :back
  end

  def show
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :skill_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/mentoring/questions_controller.rb
class Mentoring::QuestionsController < ApplicationController

  def create
    @question = Question.new(question_params)

    @question.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def question_params
    params.require(:question).permit(:appointment_id, :description, :answer)
  end
end

app/controllers/mentoring/students_controller.rb
class Mentoring::StudentsController < ApplicationController
  def index
    @students = current_mentor.students
  end

  def show
    @student = Student.find(params[:id])
    @appointments = @student.appointments
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    @question = Question.new(question_params)

    @question.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def question_params
    params.require(:question).permit(:appointment_id, :description, :answer)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @new_skill = Skill.new
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
    @skill_bookmarks = @skill.bookmarks
  end

  def create
    @skill = Skill.new(skill_params)

    # Temporary Auth Logic for Mentor
    redirect_to :back and return unless current_mentor
    @skill.mentor = current_mentor

    @skill.save

    redirect_to :back
  end

  private

  def skill_params
    params.require(:skill).permit(:name, :description)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = current_mentor.students
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    # Will need a more robust solution, at some point.
    current_mentor || current_student
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shōko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "navigation/main" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="main-container">
    <%= yield %>
  </div>

</body>
</html>

app/views/navigation/_login.html.erb
<% if current_student %>
  <%= link_to "Sign Out", destroy_student_session_path, method: :delete %>
<% elsif current_mentor %>
  <%= link_to "Sign Out", destroy_mentor_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_student_session_path %>
<% end %>

app/views/navigation/_main.html.erb
  <nav>
    <div class="nav-logo-container">
      <%= link_to "SHOKO", root_path, class: "nav-logo" %>
    </div>

    <div class="nav-general-links">
      <%= link_to "Skills", skills_path %>
      <%= link_to "Bookmarks", bookmarks_path %>
      <% if current_mentor %>
        <%= link_to "Students", mentoring_students_path %>
        <%= link_to "Appointments", mentoring_appointments_path %>
      <% end %>
    </div>

    <div class="nav-session-links">
      <li><%= render "navigation/student_login" %></li>
      <li><%= render "navigation/mentor_login" %></li>
    </div>
  </nav>

app/views/navigation/_mentor_login.html.erb
<% if current_student %>

<% elsif current_mentor %>
  <%= link_to "Sign Out", destroy_mentor_session_path, method: :delete %>
<% else %>
  <%= link_to "Mentor Sign In", new_mentor_session_path %>
<% end %>

app/views/navigation/_student_login.html.erb
<% if current_student %>
  <%= link_to "Sign Out", destroy_student_session_path, method: :delete %>
<% elsif current_mentor %>

<% else %>
  <%= link_to "Student Sign In", new_student_session_path %>
<% end %>